name: lttenv
channels:
  - defaults
  - conda-forge
dependencies:
  - ca-certificates=2019.10.16
  - certifi=2019.9.11
  - libedit=3.1.20181209
  - libffi=3.2.1
  - ncurses=6.1
  - openssl=1.1.1d
  - pip=19.3.1
  - python=3.7.5
  - readline=7.0
  - setuptools=41.6.0
  - sqlite=3.30.1
  - tk=8.6.8
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
      - appdirs==1.4.3
      - arrow==0.15.4
      - cachetools==3.1.1
      - chardet==3.0.4
      - cycler==0.10.0
      - ephem==3.7.7.0
      - google-api-python-client==1.7.11
      - google-auth==1.7.1
      - google-auth-httplib2==0.0.3
      - httplib2==0.14.0
      - idna==2.8
      - kiwisolver==1.1.0
      - matplotlib==3.1.1
      - numpy==1.17.4
      - oauthlib==3.1.0
      - pandas==0.25.3
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.7
      - pyee==6.0.0
      - pyparsing==2.4.5
      - pyppeteer==0.0.25
      - python-dateutil==2.8.1
      - pytz==2019.3
      - requests==2.22.0
      - requests-oauthlib==1.3.0
      - rsa==4.0
      - scipy==1.3.2
      - seaborn==0.9.0
      - six==1.13.0
      - spotipy==2.4.4
      - supervisor==4.1.0
      - tqdm==4.38.0
      - twitter==1.18.0
      - uritemplate==3.0.0
      - urllib3==1.25.7
      - websockets==8.1
